// ********RoostGPT********
/*
Test generated by RoostGPT for test API-test-javaRest using AI Type Claude AI and AI Model claude-opus-4-5-20251101

RoostTestHash=8a1c903bf9


*/

// ********RoostGPT********
package org.petstore.example.RoostTest.openapi_configuration.auth;

import io.restassured.specification.RequestSpecification;

import java.io.IOException;
import java.io.InputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.UUID;

/**
 * UnifiedAuthHandler - A unified authentication handler for REST Assured API testing.
 *
 * This class manages security schemes defined in OpenAPI 3.0+ specifications and applies
 * appropriate authentication to REST Assured request specifications.
 *
 * Supported authentication types (based on provided specification): - Bearer Token
 * Authentication (JWT)
 *
 * The class supports both valid and invalid authentication for negative testing
 * scenarios.
 */
public class UnifiedAuthHandler {

	private static final String PROPERTIES_FILE = "openapi_configuration_auth.properties";

	private static final String ENV_PREFIX = "AUTH_";

	private final Properties properties;

	private final Map<String, SecurityScheme> securitySchemes;

	/**
	 * Constructor - Initializes the authentication handler by loading properties and
	 * registering security schemes from the OpenAPI specification.
	 */
	public UnifiedAuthHandler() {
		this.properties = new Properties();
		this.securitySchemes = new HashMap<>();
		loadProperties();
		registerOpenApi3Scheme();
	}

	/**
	 * Loads authentication credentials from the properties file. Properties can be
	 * overridden by environment variables with the AUTH_ prefix. For example,
	 * AUTH_bearerAuth_token overrides bearerAuth_token property.
	 */
	private void loadProperties() {
		try (InputStream inputStream = getClass().getClassLoader().getResourceAsStream(PROPERTIES_FILE)) {
			if (inputStream != null) {
				properties.load(inputStream);
			}
			else {
				System.err.println("Warning: " + PROPERTIES_FILE + " not found in classpath. Using defaults.");
			}
		}
		catch (IOException e) {
			System.err.println("Warning: Failed to load " + PROPERTIES_FILE + ": " + e.getMessage());
		}
	}

	/**
	 * Retrieves a property value, with environment variable override support. Environment
	 * variables take precedence over properties file values.
	 * @param key The property key (without ENV_PREFIX)
	 * @param defaultValue The default value if neither env var nor property exists
	 * @return The resolved property value
	 */
	private String getProperty(String key, String defaultValue) {
		// Check environment variable first (with AUTH_ prefix)
		String envKey = ENV_PREFIX + key;
		String envValue = System.getenv(envKey);
		if (envValue != null && !envValue.isEmpty()) {
			return envValue;
		}
		// Fall back to properties file
		return properties.getProperty(key, defaultValue);
	}

	/**
	 * Registers OpenAPI 3.0+ security schemes. This method parses the security
	 * definitions and stores them for later use.
	 *
	 * Registered schemes from specification: - bearerAuth: HTTP Bearer authentication
	 * with JWT format
	 */
	private void registerOpenApi3Scheme() {
		// Register bearerAuth - HTTP Bearer authentication with JWT
		SecurityScheme bearerAuthScheme = new SecurityScheme();
		bearerAuthScheme.setName("bearerAuth");
		bearerAuthScheme.setType("http");
		bearerAuthScheme.setScheme("bearer");
		bearerAuthScheme.setBearerFormat("JWT");
		bearerAuthScheme.setDescription(
				"JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"");
		securitySchemes.put("bearerAuth", bearerAuthScheme);
	}

	/**
	 * Applies authentication to a request specification (backward compatible overload).
	 * Defaults to "valid" authentication type.
	 * @param requestSpec The REST Assured request specification to modify
	 * @param schemeName The name of the security scheme to apply
	 * @return The modified request specification with authentication applied
	 */
	public RequestSpecification applyAuth(RequestSpecification requestSpec, String schemeName) {
		return applyAuth(requestSpec, schemeName, "valid");
	}

	/**
	 * Applies authentication to a request specification based on the specified security
	 * scheme.
	 * @param requestSpec The REST Assured request specification to modify
	 * @param schemeName The name of the security scheme to apply
	 * @param authValidityType "valid" for real credentials, "invalid" for fake
	 * credentials (for negative testing) Defaults to "valid" if null, empty, or
	 * unrecognized
	 * @return The modified request specification with authentication applied
	 */
	public RequestSpecification applyAuth(RequestSpecification requestSpec, String schemeName,
			String authValidityType) {
		// Normalize authValidityType - default to "valid" if null, empty, or unrecognized
		if (authValidityType == null || authValidityType.trim().isEmpty()) {
			authValidityType = "valid";
		}
		authValidityType = authValidityType.trim().toLowerCase();
		if (!authValidityType.equals("valid") && !authValidityType.equals("invalid")) {
			authValidityType = "valid";
		}

		SecurityScheme scheme = securitySchemes.get(schemeName);
		if (scheme == null) {
			throw new IllegalArgumentException("Unknown security scheme: " + schemeName);
		}

		String type = scheme.getType();
		String schemeType = scheme.getScheme();

		// Handle HTTP authentication schemes
		if ("http".equalsIgnoreCase(type)) {
			if ("bearer".equalsIgnoreCase(schemeType)) {
				return applyBearerAuth(requestSpec, scheme, authValidityType);
			}
		}

		throw new UnsupportedOperationException(
				"Unsupported authentication type: " + type + " with scheme: " + schemeType);
	}

	/**
	 * Applies multiple authentication schemes to a request specification (backward
	 * compatible overload). Defaults to "valid" authentication type.
	 * @param requestSpec The REST Assured request specification to modify
	 * @param schemeNames List of security scheme names to apply
	 * @return The modified request specification with all authentications applied
	 */
	public RequestSpecification applyMultipleAuth(RequestSpecification requestSpec, List<String> schemeNames) {
		return applyMultipleAuth(requestSpec, schemeNames, "valid");
	}

	/**
	 * Applies multiple authentication schemes to a request specification. Useful when an
	 * endpoint requires multiple forms of authentication.
	 * @param requestSpec The REST Assured request specification to modify
	 * @param schemeNames List of security scheme names to apply
	 * @param authValidityType "valid" for real credentials, "invalid" for fake
	 * credentials Defaults to "valid" if null, empty, or unrecognized
	 * @return The modified request specification with all authentications applied
	 */
	public RequestSpecification applyMultipleAuth(RequestSpecification requestSpec, List<String> schemeNames,
			String authValidityType) {
		// Normalize authValidityType - default to "valid" if null, empty, or unrecognized
		if (authValidityType == null || authValidityType.trim().isEmpty()) {
			authValidityType = "valid";
		}
		authValidityType = authValidityType.trim().toLowerCase();
		if (!authValidityType.equals("valid") && !authValidityType.equals("invalid")) {
			authValidityType = "valid";
		}

		RequestSpecification result = requestSpec;
		for (String schemeName : schemeNames) {
			result = applyAuth(result, schemeName, authValidityType);
		}
		return result;
	}

	/**
	 * Applies Bearer Token authentication to the request specification.
	 *
	 * For valid auth: Uses the token from properties file (bearerAuth_token) For invalid
	 * auth: Generates a random fake token for negative testing
	 * @param requestSpec The REST Assured request specification to modify
	 * @param scheme The security scheme containing bearer token configuration
	 * @param authValidityType "valid" or "invalid" (already normalized by caller)
	 * @return The modified request specification with Bearer authentication applied
	 */
	private RequestSpecification applyBearerAuth(RequestSpecification requestSpec, SecurityScheme scheme,
			String authValidityType) {
		// Normalize authValidityType as a safety measure
		if (authValidityType == null || authValidityType.trim().isEmpty()) {
			authValidityType = "valid";
		}

		String token;
		if ("invalid".equalsIgnoreCase(authValidityType)) {
			// Generate a random invalid token for negative testing
			token = generateInvalidValue("invalid_token");
		}
		else {
			// Use valid token from properties file
			token = getProperty("bearerAuth_token", "");
			if (token.isEmpty()) {
				System.err.println("Warning: Bearer token not configured for scheme: " + scheme.getName());
			}
		}

		return requestSpec.header("Authorization", "Bearer " + token);
	}

	/**
	 * Generates an invalid/random value for negative testing scenarios.
	 * @param prefix The prefix to use for the generated value
	 * @return A random string in the format: prefix_UUID
	 */
	private String generateInvalidValue(String prefix) {
		return prefix + "_" + UUID.randomUUID().toString();
	}

	/**
	 * Checks if a security scheme is registered.
	 * @param schemeName The name of the security scheme to check
	 * @return true if the scheme exists, false otherwise
	 */
	public boolean hasScheme(String schemeName) {
		return securitySchemes.containsKey(schemeName);
	}

	/**
	 * Retrieves the base URL for API requests from properties. Can be overridden by the
	 * AUTH_api_baseUrl environment variable.
	 * @return The base URL for API requests
	 */
	public String getBaseUrl() {
		return getProperty("api_baseUrl", "http://localhost:8080/OpenAPIExample/");
	}

	/**
	 * Retrieves the current environment setting from properties. Can be overridden by the
	 * AUTH_api_environment environment variable.
	 * @return The environment name (e.g., "dev", "staging", "prod")
	 */
	public String getEnvironment() {
		return getProperty("api_environment", "dev");
	}

	/**
	 * Inner class representing a security scheme definition. Stores all relevant details
	 * parsed from the OpenAPI specification.
	 */
	private static class SecurityScheme {

		private String name;

		private String type;

		private String scheme;

		private String bearerFormat;

		private String description;

		private String in;

		private String paramName;

		private String flow;

		private String authorizationUrl;

		private String tokenUrl;

		private String openIdConnectUrl;

		private Map<String, String> scopes;

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public String getType() {
			return type;
		}

		public void setType(String type) {
			this.type = type;
		}

		public String getScheme() {
			return scheme;
		}

		public void setScheme(String scheme) {
			this.scheme = scheme;
		}

		public String getBearerFormat() {
			return bearerFormat;
		}

		public void setBearerFormat(String bearerFormat) {
			this.bearerFormat = bearerFormat;
		}

		public String getDescription() {
			return description;
		}

		public void setDescription(String description) {
			this.description = description;
		}

		public String getIn() {
			return in;
		}

		public void setIn(String in) {
			this.in = in;
		}

		public String getParamName() {
			return paramName;
		}

		public void setParamName(String paramName) {
			this.paramName = paramName;
		}

		public String getFlow() {
			return flow;
		}

		public void setFlow(String flow) {
			this.flow = flow;
		}

		public String getAuthorizationUrl() {
			return authorizationUrl;
		}

		public void setAuthorizationUrl(String authorizationUrl) {
			this.authorizationUrl = authorizationUrl;
		}

		public String getTokenUrl() {
			return tokenUrl;
		}

		public void setTokenUrl(String tokenUrl) {
			this.tokenUrl = tokenUrl;
		}

		public String getOpenIdConnectUrl() {
			return openIdConnectUrl;
		}

		public void setOpenIdConnectUrl(String openIdConnectUrl) {
			this.openIdConnectUrl = openIdConnectUrl;
		}

		public Map<String, String> getScopes() {
			return scopes;
		}

		public void setScopes(Map<String, String> scopes) {
			this.scopes = scopes;
		}

	}

}
