// ********RoostGPT********
/*
Test generated by RoostGPT for test API-test-javaRest using AI Type Claude AI and AI Model claude-opus-4-5-20251101

Test generated for /orders_post for http method type POST in rest-assured framework

RoostTestHash=66b1a62d0e

[
  {
    "ScenarioID": "1",
    "TestName": "testValidOrderCreationReturns201",
    "Description": "Test creating a valid order with all required fields",
    "Execution": {
      "Arrange": "Prepare valid request body with userId, items array containing productId and quantity, shippingAddress, and valid bearer token",
      "Act": "Send POST request to /orders with valid JSON body and Authorization header",
      "Assert": "Check for 201 status, response contains id, userId, items, subtotal, shipping, total, currency, status, and createdAt"
    },
    "Validation": "Ensures API successfully creates an order with valid input and returns complete order details"
  },
  {
    "ScenarioID": "2",
    "TestName": "testOrderCreationWithMinimalRequiredFields",
    "Description": "Test creating an order with only required fields",
    "Execution": {
      "Arrange": "Prepare request body with only userId and items array with productId and quantity (minimum 1)",
      "Act": "Send POST request to /orders with minimal valid JSON body and valid auth token",
      "Assert": "Check for 201 status and response contains order id and status"
    },
    "Validation": "Ensures API accepts orders with minimal required data"
  },
  {
    "ScenarioID": "3",
    "TestName": "testOrderCreationWithMultipleItems",
    "Description": "Test creating an order with multiple items in the items array",
    "Execution": {
      "Arrange": "Prepare request body with userId and items array containing 5 different products with varying quantities",
      "Act": "Send POST request to /orders with multi-item order and valid auth token",
      "Assert": "Check for 201 status and response items array contains all submitted items"
    },
    "Validation": "Ensures API handles orders with multiple line items correctly"
  },
  {
    "ScenarioID": "4",
    "TestName": "testOrderCreationMissingAuthToken",
    "Description": "Test order creation without authorization header",
    "Execution": {
      "Arrange": "Prepare valid request body but omit Authorization header",
      "Act": "Send POST request to /orders without bearer token",
      "Assert": "Check for 401 status and response contains error code and message"
    },
    "Validation": "Ensures API rejects unauthenticated requests"
  },
  {
    "ScenarioID": "5",
    "TestName": "testOrderCreationInvalidAuthToken",
    "Description": "Test order creation with invalid/malformed bearer token",
    "Execution": {
      "Arrange": "Prepare valid request body with invalid bearer token (e.g., expired or malformed)",
      "Act": "Send POST request to /orders with Authorization: Bearer invalid_token_xyz",
      "Assert": "Check for 401 status and response contains unauthorized error message"
    },
    "Validation": "Ensures API validates authentication tokens properly"
  },
  {
    "ScenarioID": "6",
    "TestName": "testOrderCreationEmptyRequestBody",
    "Description": "Test order creation with empty request body",
    "Execution": {
      "Arrange": "Prepare empty JSON object {} as request body with valid auth token",
      "Act": "Send POST request to /orders with empty body",
      "Assert": "Check for 400 status and response contains error details about missing required fields"
    },
    "Validation": "Ensures API validates presence of required fields"
  },
  {
    "ScenarioID": "7",
    "TestName": "testOrderCreationEmptyItemsArray",
    "Description": "Test order creation with empty items array",
    "Execution": {
      "Arrange": "Prepare request body with userId but items as empty array []",
      "Act": "Send POST request to /orders with empty items array and valid auth token",
      "Assert": "Check for 400 status and response indicates items array cannot be empty"
    },
    "Validation": "Ensures API rejects orders without any items"
  },
  {
    "ScenarioID": "8",
    "TestName": "testOrderCreationMissingProductId",
    "Description": "Test order creation with item missing productId",
    "Execution": {
      "Arrange": "Prepare request body with items array containing object with only quantity, no productId",
      "Act": "Send POST request to /orders with incomplete item data",
      "Assert": "Check for 400 status and response details indicate productId is required"
    },
    "Validation": "Ensures API validates required productId field in items"
  },
  {
    "ScenarioID": "9",
    "TestName": "testOrderCreationMissingQuantity",
    "Description": "Test order creation with item missing quantity",
    "Execution": {
      "Arrange": "Prepare request body with items array containing object with only productId, no quantity",
      "Act": "Send POST request to /orders with missing quantity field",
      "Assert": "Check for 400 status and response details indicate quantity is required"
    },
    "Validation": "Ensures API validates required quantity field in items"
  },
  {
    "ScenarioID": "10",
    "TestName": "testOrderCreationQuantityZero",
    "Description": "Test order creation with quantity set to 0",
    "Execution": {
      "Arrange": "Prepare request body with items array containing productId and quantity: 0",
      "Act": "Send POST request to /orders with zero quantity",
      "Assert": "Check for 400 status and response indicates quantity must be minimum 1"
    },
    "Validation": "Ensures API enforces minimum quantity constraint of 1"
  },
  {
    "ScenarioID": "11",
    "TestName": "testOrderCreationNegativeQuantity",
    "Description": "Test order creation with negative quantity value",
    "Execution": {
      "Arrange": "Prepare request body with items array containing productId and quantity: -5",
      "Act": "Send POST request to /orders with negative quantity",
      "Assert": "Check for 400 status and response indicates invalid quantity value"
    },
    "Validation": "Ensures API rejects negative quantity values"
  },
  {
    "ScenarioID": "12",
    "TestName": "testOrderCreationQuantityAsString",
    "Description": "Test order creation with quantity as string instead of integer",
    "Execution": {
      "Arrange": "Prepare request body with items array containing quantity: \"five\" instead of integer",
      "Act": "Send POST request to /orders with wrong type for quantity",
      "Assert": "Check for 400 status and response indicates type mismatch for quantity"
    },
    "Validation": "Ensures API validates quantity field type as integer"
  },
  {
    "ScenarioID": "13",
    "TestName": "testOrderCreationQuantityAsFloat",
    "Description": "Test order creation with quantity as decimal number",
    "Execution": {
      "Arrange": "Prepare request body with items array containing quantity: 2.5",
      "Act": "Send POST request to /orders with float quantity",
      "Assert": "Check for 400 status or 201 with truncated/rounded quantity"
    },
    "Validation": "Ensures API handles non-integer quantity appropriately"
  },
  {
    "ScenarioID": "14",
    "TestName": "testOrderCreationNullUserId",
    "Description": "Test order creation with null userId",
    "Execution": {
      "Arrange": "Prepare request body with userId: null and valid items array",
      "Act": "Send POST request to /orders with null userId",
      "Assert": "Check for 400 status and response indicates userId cannot be null"
    },
    "Validation": "Ensures API rejects null values for userId"
  },
  {
    "ScenarioID": "15",
    "TestName": "testOrderCreationNullProductId",
    "Description": "Test order creation with null productId in items",
    "Execution": {
      "Arrange": "Prepare request body with items array containing productId: null and valid quantity",
      "Act": "Send POST request to /orders with null productId",
      "Assert": "Check for 400 status and response indicates productId cannot be null"
    },
    "Validation": "Ensures API rejects null values for required productId"
  },
  {
    "ScenarioID": "16",
    "TestName": "testOrderCreationNullQuantity",
    "Description": "Test order creation with null quantity in items",
    "Execution": {
      "Arrange": "Prepare request body with items array containing valid productId and quantity: null",
      "Act": "Send POST request to /orders with null quantity",
      "Assert": "Check for 400 status and response indicates quantity cannot be null"
    },
    "Validation": "Ensures API rejects null values for required quantity"
  },
  {
    "ScenarioID": "17",
    "TestName": "testOrderCreationWithCompleteShippingAddress",
    "Description": "Test order creation with full shipping address details",
    "Execution": {
      "Arrange": "Prepare request body with complete shippingAddress including line1, line2, city, state, postalCode, country",
      "Act": "Send POST request to /orders with full address and valid auth token",
      "Assert": "Check for 201 status and response shippingAddress matches submitted data"
    },
    "Validation": "Ensures API correctly stores complete shipping address"
  },
  {
    "ScenarioID": "18",
    "TestName": "testOrderCreationWithPartialShippingAddress",
    "Description": "Test order creation with partial shipping address",
    "Execution": {
      "Arrange": "Prepare request body with shippingAddress containing only line1 and city",
      "Act": "Send POST request to /orders with partial address",
      "Assert": "Check for 201 status and response contains partial address data"
    },
    "Validation": "Ensures API accepts partial shipping address information"
  },
  {
    "ScenarioID": "19",
    "TestName": "testOrderCreationWithNegativeUnitPrice",
    "Description": "Test order creation with negative unitPrice in items",
    "Execution": {
      "Arrange": "Prepare request body with items containing unitPrice: -10.99",
      "Act": "Send POST request to /orders with negative unit price",
      "Assert": "Check for 400 status and response indicates invalid unitPrice"
    },
    "Validation": "Ensures API rejects negative price values"
  },
  {
    "ScenarioID": "20",
    "TestName": "testOrderCreationWithUnitPriceAsString",
    "Description": "Test order creation with unitPrice as string type",
    "Execution": {
      "Arrange": "Prepare request body with items containing unitPrice: \"19.99\" as string",
      "Act": "Send POST request to /orders with string unitPrice",
      "Assert": "Check for 400 status indicating type mismatch or 201 if API coerces type"
    },
    "Validation": "Ensures API validates unitPrice field type as number"
  },
  {
    "ScenarioID": "21",
    "TestName": "testOrderCreationMalformedJson",
    "Description": "Test order creation with malformed JSON body",
    "Execution": {
      "Arrange": "Prepare malformed JSON string with missing closing brace or invalid syntax",
      "Act": "Send POST request to /orders with malformed JSON body",
      "Assert": "Check for 400 status and response indicates JSON parse error"
    },
    "Validation": "Ensures API handles malformed JSON gracefully"
  },
  {
    "ScenarioID": "22",
    "TestName": "testOrderCreationWrongContentType",
    "Description": "Test order creation with incorrect Content-Type header",
    "Execution": {
      "Arrange": "Prepare valid JSON body but set Content-Type to text/plain",
      "Act": "Send POST request to /orders with wrong Content-Type header",
      "Assert": "Check for 400 or 415 status indicating unsupported media type"
    },
    "Validation": "Ensures API validates Content-Type header"
  },
  {
    "ScenarioID": "23",
    "TestName": "testOrderCreationItemsAsObject",
    "Description": "Test order creation with items as object instead of array",
    "Execution": {
      "Arrange": "Prepare request body with items as single object instead of array",
      "Act": "Send POST request to /orders with items: {productId: \"p1\", quantity: 1}",
      "Assert": "Check for 400 status and response indicates items must be an array"
    },
    "Validation": "Ensures API validates items field type as array"
  },
  {
    "ScenarioID": "24",
    "TestName": "testOrderCreationItemsAsString",
    "Description": "Test order creation with items as string",
    "Execution": {
      "Arrange": "Prepare request body with items: \"product1,product2\"",
      "Act": "Send POST request to /orders with string items",
      "Assert": "Check for 400 status and response indicates type mismatch"
    },
    "Validation": "Ensures API rejects non-array items field"
  },
  {
    "ScenarioID": "25",
    "TestName": "testOrderCreationVeryLargeQuantity",
    "Description": "Test order creation with extremely large quantity value",
    "Execution": {
      "Arrange": "Prepare request body with items containing quantity: 999999999",
      "Act": "Send POST request to /orders with very large quantity",
      "Assert": "Check for 201 status or 400 if quantity exceeds allowed maximum"
    },
    "Validation": "Ensures API handles boundary values for quantity"
  },
  {
    "ScenarioID": "26",
    "TestName": "testOrderCreationEmptyStringUserId",
    "Description": "Test order creation with empty string userId",
    "Execution": {
      "Arrange": "Prepare request body with userId: \"\" and valid items",
      "Act": "Send POST request to /orders with empty userId",
      "Assert": "Check for 400 status and response indicates userId cannot be empty"
    },
    "Validation": "Ensures API validates userId is not empty string"
  },
  {
    "ScenarioID": "27",
    "TestName": "testOrderCreationEmptyStringProductId",
    "Description": "Test order creation with empty string productId",
    "Execution": {
      "Arrange": "Prepare request body with items containing productId: \"\"",
      "Act": "Send POST request to /orders with empty productId",
      "Assert": "Check for 400 status and response indicates productId cannot be empty"
    },
    "Validation": "Ensures API validates productId is not empty string"
  },
  {
    "ScenarioID": "28",
    "TestName": "testOrderCreationExpiredToken",
    "Description": "Test order creation with expired bearer token",
    "Execution": {
      "Arrange": "Prepare valid request body with expired JWT bearer token",
      "Act": "Send POST request to /orders with expired token in Authorization header",
      "Assert": "Check for 401 status and response indicates token expired"
    },
    "Validation": "Ensures API properly validates token expiration"
  },
  {
    "ScenarioID": "29",
    "TestName": "testOrderCreationWithSpecialCharactersInUserId",
    "Description": "Test order creation with special characters in userId",
    "Execution": {
      "Arrange": "Prepare request body with userId containing special chars like <script>alert(1)</script>",
      "Act": "Send POST request to /orders with special characters in userId",
      "Assert": "Check for 400 status or 201 with sanitized data"
    },
    "Validation": "Ensures API handles potential XSS injection in userId"
  },
  {
    "ScenarioID": "30",
    "TestName": "testOrderCreationWithSQLInjectionInProductId",
    "Description": "Test order creation with SQL injection attempt in productId",
    "Execution": {
      "Arrange": "Prepare request body with productId: \"1; DROP TABLE orders;--\"",
      "Act": "Send POST request to /orders with SQL injection payload",
      "Assert": "Check for 400 status or 201 with sanitized/escaped data"
    },
    "Validation": "Ensures API is protected against SQL injection attacks"
  },
  {
    "ScenarioID": "31",
    "TestName": "testOrderCreationResponseContainsCreatedAt",
    "Description": "Test that successful order creation returns valid createdAt timestamp",
    "Execution": {
      "Arrange": "Prepare valid order request body with auth token",
      "Act": "Send POST request to /orders with valid data",
      "Assert": "Check for 201 status and createdAt field is valid ISO 8601 date-time format"
    },
    "Validation": "Ensures API returns properly formatted timestamp"
  },
  {
    "ScenarioID": "32",
    "TestName": "testOrderCreationResponseStatusIsPending",
    "Description": "Test that new order status is set to PENDING",
    "Execution": {
      "Arrange": "Prepare valid order request body with auth token",
      "Act": "Send POST request to /orders with valid data",
      "Assert": "Check for 201 status and response status field equals \"PENDING\""
    },
    "Validation": "Ensures new orders are created with correct initial status"
  },
  {
    "ScenarioID": "33",
    "TestName": "testOrderCreationWithExtraUnknownFields",
    "Description": "Test order creation with additional unknown fields in request body",
    "Execution": {
      "Arrange": "Prepare valid request body with extra fields like unknownField: \"test\"",
      "Act": "Send POST request to /orders with extra fields",
      "Assert": "Check for 201 status and unknown fields are ignored or 400 if strict validation"
    },
    "Validation": "Ensures API handles unknown fields appropriately"
  },
  {
    "ScenarioID": "34",
    "TestName": "testOrderCreationWithDuplicateProductIds",
    "Description": "Test order creation with same productId appearing multiple times in items",
    "Execution": {
      "Arrange": "Prepare request body with items array containing same productId twice with different quantities",
      "Act": "Send POST request to /orders with duplicate productIds",
      "Assert": "Check for 201 status with both items or 400 if duplicates not allowed"
    },
    "Validation": "Ensures API handles duplicate product entries correctly"
  },
  {
    "ScenarioID": "35",
    "TestName": "testOrderCreationWithVeryLongProductId",
    "Description": "Test order creation with extremely long productId string",
    "Execution": {
      "Arrange": "Prepare request body with productId containing 10000 characters",
      "Act": "Send POST request to /orders with very long productId",
      "Assert": "Check for 400 status indicating field length exceeded or 201 if accepted"
    },
    "Validation": "Ensures API handles boundary conditions for string length"
  }
]

*/

// ********RoostGPT********
package org.petstore.example.RoostTest.openapi_configuration;

import org.petstore.example.RoostTest.openapi_configuration.auth.UnifiedAuthHandler;
import org.petstore.example.RoostTest.openapi_configuration.utils.ResponseValidator;
import org.petstore.example.RoostTest.openapi_configuration.utils.SchemaModels.ResponseSchema;
import org.petstore.example.RoostTest.openapi_configuration.utils.SchemaModels.FieldConstraint;
import org.petstore.example.RoostTest.openapi_configuration.utils.SchemaModels.NumericConstraint;
import org.petstore.example.RoostTest.openapi_configuration.utils.SchemaModels.StringConstraint;
import org.petstore.example.RoostTest.openapi_configuration.utils.SchemaModels.ArrayConstraint;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import io.restassured.http.ContentType;
import static io.restassured.RestAssured.given;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.File;
import java.io.IOException;
import java.util.*;
import java.util.stream.Stream;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class OrdersPostTest {

	private static final Logger logger = LoggerFactory.getLogger(OrdersPostTest.class);

	private UnifiedAuthHandler authHandler;

	private ResponseValidator responseValidator;

	private ObjectMapper objectMapper;

	private static final String BASE_URI = "http://localhost:8080/OpenAPIExample/";

	private static final String ENDPOINT = "/orders";

	private static final String HTTP_METHOD = "post";

	private static final String TEST_DATA_FILE = "src/test/java/org/petstore/example/RoostTest/openapi_configuration/datasets/ordersPostTest.json";

	private Map<String, ParameterInfo> parameters;

	private SecurityInfo security;

	private Map<Integer, ResponseSchema> schemas;

	@BeforeAll
	public void setup() {
		authHandler = new UnifiedAuthHandler();
		responseValidator = new ResponseValidator();
		objectMapper = new ObjectMapper();

		String baseUrl = authHandler.getBaseUrl();
		if (baseUrl == null || baseUrl.isEmpty()) {
			RestAssured.baseURI = BASE_URI;
		}
		else {
			RestAssured.baseURI = baseUrl;
		}

		parameters = getParameters();
		security = getSecurityInfo();
		schemas = getResponseSchemas();

		logger.info("✓ Test setup completed. Base URI: {}", RestAssured.baseURI);
	}

	public Stream<TestScenario> testScenarioProvider() {
		List<Map<String, Object>> testCases = loadTestData();
		if (testCases == null || testCases.isEmpty()) {
			logger.warn("✗ No test cases found in: {}", TEST_DATA_FILE);
			return Stream.empty();
		}

		int[] index = { 0 };
		return testCases.stream().map(testCase -> {
			index[0]++;
			String scenarioId = String.valueOf(index[0]);
			String scenarioDescription = testCase.containsKey("scenario") ? String.valueOf(testCase.get("scenario"))
					: "Test case " + scenarioId;
			String testName = generateTestName(scenarioDescription, testCase);
			return new TestScenario(scenarioId, testName, scenarioDescription, testCase);
		});
	}

	private String generateTestName(String scenario, Map<String, Object> testCase) {
		Object statusCodeObj = testCase.get("expected_statusCode");
		String statusCode = statusCodeObj != null ? String.valueOf(((Number) statusCodeObj).intValue()) : "unknown";

		String sanitized = scenario.replaceAll("[^a-zA-Z0-9\\s]", "").replaceAll("\\s+", "_").toLowerCase();

		if (sanitized.length() > 50) {
			sanitized = sanitized.substring(0, 50);
		}

		return "test_" + sanitized + "_" + statusCode;
	}

	@ParameterizedTest(name = "[{index}] {0}")
	@MethodSource("testScenarioProvider")
	public void testEndpoint(TestScenario scenario) {
		logger.info("▶ Starting test: {} - {}", scenario.scenarioId, scenario.testName);

		Map<String, Object> testCase = scenario.testCase;
		Object statusCodeObj = testCase.get("expected_statusCode");

		if (statusCodeObj == null) {
			logger.error("✗ Missing expected_statusCode in test case: {}", scenario.scenarioId);
			throw new AssertionError("Missing expected_statusCode in test case");
		}

		int expectedStatusCode = ((Number) statusCodeObj).intValue();
		String authValidityType = (expectedStatusCode == 401) ? "invalid" : "valid";

		logger.info("  Auth validity type: {} (expected status: {})", authValidityType, expectedStatusCode);

		Response response = executeTest(testCase, parameters, security, authValidityType);

		ResponseSchema schema = schemas.get(expectedStatusCode);
		if (schema == null) {
			schema = schemas.get(0);
		}

		String contentType = response.getHeader("Content-Type");

		if (contentType != null && contentType.contains("application/json")) {
			responseValidator.validateResponse(response, expectedStatusCode, schema);
			logger.info("✓ Response validation completed for scenario: {}", scenario.scenarioId);
		}
		else {
			if (response.getStatusCode() == expectedStatusCode) {
				logger.info("✓ Status code matches: {}", expectedStatusCode);
			}
			else {
				throw new AssertionError("Status code mismatch. Expected: " + expectedStatusCode + ", Actual: "
						+ response.getStatusCode());
			}
		}

		logger.info("✓ Test passed: {} - {}", scenario.testName, scenario.scenarioId);
	}

	private Response executeTest(Map<String, Object> testCase, Map<String, ParameterInfo> parameters,
			SecurityInfo security, String authValidityType) {
		Map<String, Object> queryParams = new HashMap<>();
		Map<String, Object> pathParams = new HashMap<>();
		Map<String, Object> headerParams = new HashMap<>();
		Object requestBody = null;

		for (Map.Entry<String, Object> entry : testCase.entrySet()) {
			String key = entry.getKey();
			Object value = entry.getValue();

			if (key.equals("scenario") || key.equals("expected_statusCode") || key.equals("ScenarioID")
					|| key.equals("TestName") || key.equals("Description") || key.equals("Execution")
					|| key.equals("Validation")) {
				continue;
			}

			if (value == null) {
				continue;
			}

			if (key.equals("headers") && value instanceof Map) {
				@SuppressWarnings("unchecked")
				Map<String, Object> headers = (Map<String, Object>) value;
				for (Map.Entry<String, Object> headerEntry : headers.entrySet()) {
					if (headerEntry.getValue() != null) {
						headerParams.put(headerEntry.getKey(), headerEntry.getValue());
					}
				}
				continue;
			}

			if (key.equals("query") && value instanceof Map) {
				@SuppressWarnings("unchecked")
				Map<String, Object> query = (Map<String, Object>) value;
				for (Map.Entry<String, Object> queryEntry : query.entrySet()) {
					if (queryEntry.getValue() != null) {
						queryParams.put(queryEntry.getKey(), queryEntry.getValue());
					}
				}
				continue;
			}

			if (key.equals("path") && value instanceof Map) {
				@SuppressWarnings("unchecked")
				Map<String, Object> path = (Map<String, Object>) value;
				for (Map.Entry<String, Object> pathEntry : path.entrySet()) {
					if (pathEntry.getValue() != null) {
						pathParams.put(pathEntry.getKey(), pathEntry.getValue());
					}
				}
				continue;
			}

			if (key.equals("body") || key.equals("requestBody")) {
				requestBody = value;
				continue;
			}

			ParameterInfo paramInfo = parameters.get(key);
			if (paramInfo != null) {
				switch (paramInfo.getLocation()) {
					case "query":
						queryParams.put(key, value);
						break;
					case "path":
						pathParams.put(key, value);
						break;
					case "header":
						headerParams.put(key, value);
						break;
					default:
						break;
				}
			}
			else {
				if (requestBody == null && (value instanceof Map || value instanceof List)) {
					requestBody = value;
				}
			}
		}

		if (requestBody == null) {
			Map<String, Object> bodyCandidate = new HashMap<>();
			for (Map.Entry<String, Object> entry : testCase.entrySet()) {
				String key = entry.getKey();
				if (!key.equals("scenario") && !key.equals("expected_statusCode") && !key.equals("ScenarioID")
						&& !key.equals("TestName") && !key.equals("Description") && !key.equals("Execution")
						&& !key.equals("Validation") && !key.equals("headers") && !key.equals("query")
						&& !key.equals("path") && parameters.get(key) == null && entry.getValue() != null) {
					bodyCandidate.put(key, entry.getValue());
				}
			}
			if (!bodyCandidate.isEmpty()) {
				requestBody = bodyCandidate;
			}
		}

		RequestSpecification request = given().contentType(ContentType.JSON).accept(ContentType.JSON);

		if (security != null && security.getSchemeName() != null) {
			request = authHandler.applyAuth(request, security.getSchemeName(), authValidityType);
		}

		if (!queryParams.isEmpty()) {
			request = request.queryParams(queryParams);
		}

		if (!pathParams.isEmpty()) {
			request = request.pathParams(pathParams);
		}

		if (!headerParams.isEmpty()) {
			request = request.headers(headerParams);
		}

		if (requestBody != null) {
			request = request.body(requestBody);
		}

		logger.info("  Executing {} request to {}", HTTP_METHOD.toUpperCase(), ENDPOINT);
		logger.info("  Query params: {}", queryParams);
		logger.info("  Path params: {}", pathParams);
		logger.info("  Header params: {}", headerParams);
		logger.info("  Request body: {}", requestBody);

		Response response = request.when().post(ENDPOINT);

		logger.info("  Response status: {}", response.getStatusCode());
		logger.info("  Response body: {}", response.getBody().asString());

		return response;
	}

	private Map<String, ParameterInfo> getParameters() {
		Map<String, ParameterInfo> params = new HashMap<>();
		return params;
	}

	private SecurityInfo getSecurityInfo() {
		return new SecurityInfo("bearerAuth", "http", "bearer", "header");
	}

	private Map<Integer, ResponseSchema> getResponseSchemas() {
		Map<Integer, ResponseSchema> schemaMap = new HashMap<>();

		// Schema for 201 response
		ResponseSchema schema201 = new ResponseSchema();
		Map<String, FieldConstraint> fields201 = new HashMap<>();

		fields201.put("id", new FieldConstraint("string"));
		fields201.put("userId", new FieldConstraint("string"));

		FieldConstraint itemsField = new FieldConstraint("array");
		FieldConstraint itemConstraint = new FieldConstraint("object");
		Map<String, FieldConstraint> itemNestedFields = new HashMap<>();
		itemNestedFields.put("productId", new FieldConstraint("string"));
		FieldConstraint quantityField = new FieldConstraint("integer");
		quantityField.setNumericConstraint(new NumericConstraint().setMinimum(1));
		itemNestedFields.put("quantity", quantityField);
		itemNestedFields.put("unitPrice", new FieldConstraint("number").setFormat("float"));
		itemConstraint.setNestedFields(itemNestedFields);
		itemConstraint.setNestedRequired(Arrays.asList("productId", "quantity"));
		itemsField.setItemsConstraint(itemConstraint);
		fields201.put("items", itemsField);

		fields201.put("subtotal", new FieldConstraint("number").setFormat("float"));
		fields201.put("shipping", new FieldConstraint("number").setFormat("float"));
		fields201.put("total", new FieldConstraint("number").setFormat("float"));
		fields201.put("currency", new FieldConstraint("string"));
		fields201.put("status", new FieldConstraint("string"));

		FieldConstraint shippingAddressField = new FieldConstraint("object");
		Map<String, FieldConstraint> addressNestedFields = new HashMap<>();
		addressNestedFields.put("line1", new FieldConstraint("string"));
		addressNestedFields.put("line2", new FieldConstraint("string"));
		addressNestedFields.put("city", new FieldConstraint("string"));
		addressNestedFields.put("state", new FieldConstraint("string"));
		addressNestedFields.put("postalCode", new FieldConstraint("string"));
		addressNestedFields.put("country", new FieldConstraint("string"));
		shippingAddressField.setNestedFields(addressNestedFields);
		fields201.put("shippingAddress", shippingAddressField);

		fields201.put("createdAt", new FieldConstraint("string").setFormat("date-time"));

		schema201.setFields(fields201);
		schemaMap.put(201, schema201);

		// Schema for 400 response
		ResponseSchema schema400 = new ResponseSchema();
		Map<String, FieldConstraint> fields400 = new HashMap<>();
		fields400.put("code", new FieldConstraint("integer"));
		fields400.put("message", new FieldConstraint("string"));
		FieldConstraint detailsField400 = new FieldConstraint("array");
		detailsField400.setItemsConstraint(new FieldConstraint("string"));
		fields400.put("details", detailsField400);
		schema400.setFields(fields400);
		schemaMap.put(400, schema400);

		// Schema for 401 response
		ResponseSchema schema401 = new ResponseSchema();
		Map<String, FieldConstraint> fields401 = new HashMap<>();
		fields401.put("code", new FieldConstraint("integer"));
		fields401.put("message", new FieldConstraint("string"));
		FieldConstraint detailsField401 = new FieldConstraint("array");
		detailsField401.setItemsConstraint(new FieldConstraint("string"));
		fields401.put("details", detailsField401);
		schema401.setFields(fields401);
		schemaMap.put(401, schema401);

		return schemaMap;
	}

	private List<Map<String, Object>> loadTestData() {
		try {
			File file = new File(TEST_DATA_FILE);
			if (!file.exists()) {
				logger.error("✗ Test data file not found: {}", TEST_DATA_FILE);
				return new ArrayList<>();
			}
			return objectMapper.readValue(file, new TypeReference<List<Map<String, Object>>>() {
			});
		}
		catch (IOException e) {
			logger.error("✗ Failed to load test data from {}: {}", TEST_DATA_FILE, e.getMessage());
			return new ArrayList<>();
		}
	}

	private static class TestScenario {

		private final String scenarioId;

		private final String testName;

		private final String description;

		private final Map<String, Object> testCase;

		public TestScenario(String scenarioId, String testName, String description, Map<String, Object> testCase) {
			this.scenarioId = scenarioId;
			this.testName = testName;
			this.description = description;
			this.testCase = testCase;
		}

		@Override
		public String toString() {
			return scenarioId + " - " + testName;
		}

	}

	private static class ParameterInfo {

		private final String name;

		private final String location;

		private final String type;

		private final boolean required;

		public ParameterInfo(String name, String location, String type, boolean required) {
			this.name = name;
			this.location = location;
			this.type = type;
			this.required = required;
		}

		public String getName() {
			return name;
		}

		public String getLocation() {
			return location;
		}

		public String getType() {
			return type;
		}

		public boolean isRequired() {
			return required;
		}

	}

	private static class SecurityInfo {

		private final String schemeName;

		private final String type;

		private final String credentialName;

		private final String location;

		public SecurityInfo(String schemeName, String type, String credentialName, String location) {
			this.schemeName = schemeName;
			this.type = type;
			this.credentialName = credentialName;
			this.location = location;
		}

		public String getSchemeName() {
			return schemeName;
		}

		public String getType() {
			return type;
		}

		public String getCredentialName() {
			return credentialName;
		}

		public String getLocation() {
			return location;
		}

	}

}
