// ********RoostGPT********
/*
Test generated by RoostGPT for test API-test-javaRest using AI Type Claude AI and AI Model claude-opus-4-5-20251101

Test generated for /products_post for http method type POST in rest-assured framework

RoostTestHash=852b4cd5cf

[
  {
    "ScenarioID": "1",
    "TestName": "testValidProductCreationReturns201",
    "Description": "Test creating a product with all valid fields",
    "Execution": {
      "Arrange": "Prepare valid request body with name, description, price, currency, and available fields. Include valid bearer auth token in headers",
      "Act": "Send POST request to /products with valid JSON body and Authorization header",
      "Assert": "Check for 201 status, response contains id, name, description, price, currency, available, and createdAt fields"
    },
    "Validation": "Ensures API successfully creates a product with valid input and returns proper response structure"
  },
  {
    "ScenarioID": "2",
    "TestName": "testProductCreationWithMinimalRequiredFields",
    "Description": "Test creating a product with only required fields",
    "Execution": {
      "Arrange": "Prepare request body with only name and price fields. Include valid bearer auth token",
      "Act": "Send POST request to /products with minimal JSON body",
      "Assert": "Check for 201 status and response contains generated id and provided fields"
    },
    "Validation": "Ensures API accepts minimal valid input for product creation"
  },
  {
    "ScenarioID": "3",
    "TestName": "testProductCreationMissingAuthToken",
    "Description": "Test creating a product without authentication token",
    "Execution": {
      "Arrange": "Prepare valid request body but do not include Authorization header",
      "Act": "Send POST request to /products without bearer token",
      "Assert": "Check for 401 Unauthorized status"
    },
    "Validation": "Ensures API rejects unauthenticated requests"
  },
  {
    "ScenarioID": "4",
    "TestName": "testProductCreationInvalidAuthToken",
    "Description": "Test creating a product with invalid authentication token",
    "Execution": {
      "Arrange": "Prepare valid request body with invalid or malformed bearer token",
      "Act": "Send POST request to /products with invalid Authorization header",
      "Assert": "Check for 401 or 403 status indicating authentication failure"
    },
    "Validation": "Ensures API properly validates authentication tokens"
  },
  {
    "ScenarioID": "5",
    "TestName": "testProductCreationExpiredAuthToken",
    "Description": "Test creating a product with expired authentication token",
    "Execution": {
      "Arrange": "Prepare valid request body with expired bearer token",
      "Act": "Send POST request to /products with expired Authorization header",
      "Assert": "Check for 401 status indicating token expiration"
    },
    "Validation": "Ensures API rejects expired authentication tokens"
  },
  {
    "ScenarioID": "6",
    "TestName": "testProductCreationEmptyRequestBody",
    "Description": "Test creating a product with empty request body",
    "Execution": {
      "Arrange": "Prepare empty JSON object {} as request body with valid auth token",
      "Act": "Send POST request to /products with empty body",
      "Assert": "Check for 400 status with error message indicating missing required fields"
    },
    "Validation": "Ensures API validates presence of required fields"
  },
  {
    "ScenarioID": "7",
    "TestName": "testProductCreationNullRequestBody",
    "Description": "Test creating a product with null request body",
    "Execution": {
      "Arrange": "Send null as request body with valid auth token",
      "Act": "Send POST request to /products with null body",
      "Assert": "Check for 400 status with appropriate error message"
    },
    "Validation": "Ensures API handles null request body gracefully"
  },
  {
    "ScenarioID": "8",
    "TestName": "testProductCreationMissingName",
    "Description": "Test creating a product without name field",
    "Execution": {
      "Arrange": "Prepare request body with price, description but missing name field",
      "Act": "Send POST request to /products",
      "Assert": "Check for 400 status with details array indicating name is required"
    },
    "Validation": "Ensures API validates required name field"
  },
  {
    "ScenarioID": "9",
    "TestName": "testProductCreationEmptyName",
    "Description": "Test creating a product with empty string name",
    "Execution": {
      "Arrange": "Prepare request body with name as empty string",
      "Act": "Send POST request to /products with name: ''",
      "Assert": "Check for 400 status indicating invalid name"
    },
    "Validation": "Ensures API rejects empty product names"
  },
  {
    "ScenarioID": "10",
    "TestName": "testProductCreationNullName",
    "Description": "Test creating a product with null name",
    "Execution": {
      "Arrange": "Prepare request body with name: null",
      "Act": "Send POST request to /products",
      "Assert": "Check for 400 status with error details"
    },
    "Validation": "Ensures API rejects null name values"
  },
  {
    "ScenarioID": "11",
    "TestName": "testProductCreationNameWrongType",
    "Description": "Test creating a product with name as number instead of string",
    "Execution": {
      "Arrange": "Prepare request body with name: 12345 (number type)",
      "Act": "Send POST request to /products",
      "Assert": "Check for 400 status indicating type mismatch"
    },
    "Validation": "Ensures API validates name field type"
  },
  {
    "ScenarioID": "12",
    "TestName": "testProductCreationNegativePrice",
    "Description": "Test creating a product with negative price",
    "Execution": {
      "Arrange": "Prepare request body with price: -29.99",
      "Act": "Send POST request to /products",
      "Assert": "Check for 400 status indicating invalid price value"
    },
    "Validation": "Ensures API rejects negative price values"
  },
  {
    "ScenarioID": "13",
    "TestName": "testProductCreationZeroPrice",
    "Description": "Test creating a product with zero price",
    "Execution": {
      "Arrange": "Prepare request body with price: 0",
      "Act": "Send POST request to /products",
      "Assert": "Check for 201 status or 400 depending on business rules"
    },
    "Validation": "Ensures API handles zero price according to business logic"
  },
  {
    "ScenarioID": "14",
    "TestName": "testProductCreationPriceAsString",
    "Description": "Test creating a product with price as string instead of number",
    "Execution": {
      "Arrange": "Prepare request body with price: '29.99' (string type)",
      "Act": "Send POST request to /products",
      "Assert": "Check for 400 status indicating type mismatch"
    },
    "Validation": "Ensures API validates price field type as number"
  },
  {
    "ScenarioID": "15",
    "TestName": "testProductCreationPriceNull",
    "Description": "Test creating a product with null price",
    "Execution": {
      "Arrange": "Prepare request body with price: null",
      "Act": "Send POST request to /products",
      "Assert": "Check for 400 status indicating price is required or invalid"
    },
    "Validation": "Ensures API handles null price appropriately"
  },
  {
    "ScenarioID": "16",
    "TestName": "testProductCreationPriceVeryLargeNumber",
    "Description": "Test creating a product with extremely large price value",
    "Execution": {
      "Arrange": "Prepare request body with price: 999999999999999.99",
      "Act": "Send POST request to /products",
      "Assert": "Check for 201 or 400 status depending on max value constraints"
    },
    "Validation": "Ensures API handles large price values correctly"
  },
  {
    "ScenarioID": "17",
    "TestName": "testProductCreationAvailableWrongType",
    "Description": "Test creating a product with available as string instead of boolean",
    "Execution": {
      "Arrange": "Prepare request body with available: 'true' (string type)",
      "Act": "Send POST request to /products",
      "Assert": "Check for 400 status indicating type mismatch"
    },
    "Validation": "Ensures API validates available field type as boolean"
  },
  {
    "ScenarioID": "18",
    "TestName": "testProductCreationAvailableAsNumber",
    "Description": "Test creating a product with available as number",
    "Execution": {
      "Arrange": "Prepare request body with available: 1",
      "Act": "Send POST request to /products",
      "Assert": "Check for 400 status indicating type mismatch"
    },
    "Validation": "Ensures API strictly validates boolean type for available field"
  },
  {
    "ScenarioID": "19",
    "TestName": "testProductCreationInvalidCurrency",
    "Description": "Test creating a product with invalid currency code",
    "Execution": {
      "Arrange": "Prepare request body with currency: 'INVALID'",
      "Act": "Send POST request to /products",
      "Assert": "Check for 400 status if currency validation exists, or 201 if no validation"
    },
    "Validation": "Ensures API validates currency codes if applicable"
  },
  {
    "ScenarioID": "20",
    "TestName": "testProductCreationEmptyCurrency",
    "Description": "Test creating a product with empty currency string",
    "Execution": {
      "Arrange": "Prepare request body with currency: ''",
      "Act": "Send POST request to /products",
      "Assert": "Check for 400 status indicating invalid currency"
    },
    "Validation": "Ensures API rejects empty currency values"
  },
  {
    "ScenarioID": "21",
    "TestName": "testProductCreationMalformedJson",
    "Description": "Test creating a product with malformed JSON body",
    "Execution": {
      "Arrange": "Prepare malformed JSON string: {name: 'test', price: 10} (missing quotes)",
      "Act": "Send POST request to /products with malformed JSON",
      "Assert": "Check for 400 status indicating JSON parse error"
    },
    "Validation": "Ensures API handles malformed JSON gracefully"
  },
  {
    "ScenarioID": "22",
    "TestName": "testProductCreationWrongContentType",
    "Description": "Test creating a product with wrong Content-Type header",
    "Execution": {
      "Arrange": "Prepare valid JSON body but set Content-Type to text/plain",
      "Act": "Send POST request to /products with incorrect Content-Type",
      "Assert": "Check for 400 or 415 Unsupported Media Type status"
    },
    "Validation": "Ensures API validates Content-Type header"
  },
  {
    "ScenarioID": "23",
    "TestName": "testProductCreationExtraUnknownFields",
    "Description": "Test creating a product with additional unknown fields",
    "Execution": {
      "Arrange": "Prepare request body with valid fields plus unknownField: 'value'",
      "Act": "Send POST request to /products",
      "Assert": "Check for 201 status (ignores extra fields) or 400 if strict validation"
    },
    "Validation": "Ensures API handles unknown fields appropriately"
  },
  {
    "ScenarioID": "24",
    "TestName": "testProductCreationVeryLongName",
    "Description": "Test creating a product with extremely long name",
    "Execution": {
      "Arrange": "Prepare request body with name containing 10000 characters",
      "Act": "Send POST request to /products",
      "Assert": "Check for 400 status if length validation exists, or 201 if accepted"
    },
    "Validation": "Ensures API handles or limits very long string inputs"
  },
  {
    "ScenarioID": "25",
    "TestName": "testProductCreationSpecialCharactersInName",
    "Description": "Test creating a product with special characters in name",
    "Execution": {
      "Arrange": "Prepare request body with name: '<script>alert(1)</script>'",
      "Act": "Send POST request to /products",
      "Assert": "Check for 201 with sanitized output or 400 if rejected"
    },
    "Validation": "Ensures API handles XSS-like input safely"
  },
  {
    "ScenarioID": "26",
    "TestName": "testProductCreationUnicodeCharacters",
    "Description": "Test creating a product with unicode characters in name",
    "Execution": {
      "Arrange": "Prepare request body with name containing unicode: 'Producto Espanol'",
      "Act": "Send POST request to /products",
      "Assert": "Check for 201 status and response preserves unicode characters"
    },
    "Validation": "Ensures API supports international characters"
  },
  {
    "ScenarioID": "27",
    "TestName": "testProductCreationSqlInjectionAttempt",
    "Description": "Test creating a product with SQL injection in name",
    "Execution": {
      "Arrange": "Prepare request body with name: 'Product; DROP TABLE products;--'",
      "Act": "Send POST request to /products",
      "Assert": "Check for 201 with escaped content or 400 if rejected"
    },
    "Validation": "Ensures API is protected against SQL injection"
  },
  {
    "ScenarioID": "28",
    "TestName": "testProductCreationDescriptionNull",
    "Description": "Test creating a product with null description",
    "Execution": {
      "Arrange": "Prepare request body with description: null",
      "Act": "Send POST request to /products",
      "Assert": "Check for 201 status if description is optional"
    },
    "Validation": "Ensures API accepts null for optional description field"
  },
  {
    "ScenarioID": "29",
    "TestName": "testProductCreationPriceWithManyDecimals",
    "Description": "Test creating a product with price having many decimal places",
    "Execution": {
      "Arrange": "Prepare request body with price: 29.999999999",
      "Act": "Send POST request to /products",
      "Assert": "Check for 201 with rounded price or 400 if precision validation exists"
    },
    "Validation": "Ensures API handles float precision correctly"
  },
  {
    "ScenarioID": "30",
    "TestName": "testProductCreationArrayInsteadOfObject",
    "Description": "Test creating a product with array instead of object body",
    "Execution": {
      "Arrange": "Prepare request body as array: [{name: 'test'}]",
      "Act": "Send POST request to /products",
      "Assert": "Check for 400 status indicating invalid body format"
    },
    "Validation": "Ensures API validates request body structure"
  }
]

*/

// ********RoostGPT********
package org.petstore.example.RoostTest.openapi_configuration;

import org.petstore.example.RoostTest.openapi_configuration.auth.UnifiedAuthHandler;
import org.petstore.example.RoostTest.openapi_configuration.utils.ResponseValidator;
import org.petstore.example.RoostTest.openapi_configuration.utils.SchemaModels.ResponseSchema;
import org.petstore.example.RoostTest.openapi_configuration.utils.SchemaModels.FieldConstraint;
import org.petstore.example.RoostTest.openapi_configuration.utils.SchemaModels.NumericConstraint;
import org.petstore.example.RoostTest.openapi_configuration.utils.SchemaModels.StringConstraint;
import org.petstore.example.RoostTest.openapi_configuration.utils.SchemaModels.ArrayConstraint;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import io.restassured.http.ContentType;
import static io.restassured.RestAssured.given;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.File;
import java.io.IOException;
import java.util.*;
import java.util.stream.Stream;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class ProductsPostTest {

	private static final Logger logger = LoggerFactory.getLogger(ProductsPostTest.class);

	private UnifiedAuthHandler authHandler;

	private ResponseValidator responseValidator;

	private ObjectMapper objectMapper;

	private static final String BASE_URI = "http://localhost:8080/OpenAPIExample/";

	private static final String ENDPOINT = "/products";

	private static final String HTTP_METHOD = "post";

	private static final String TEST_DATA_FILE = "src/test/java/org/petstore/example/RoostTest/openapi_configuration/datasets/productsPostTest.json";

	private Map<String, ParameterInfo> parameters;

	private SecurityInfo security;

	private Map<Integer, ResponseSchema> schemas;

	@BeforeAll
	public void setup() {
		authHandler = new UnifiedAuthHandler();
		responseValidator = new ResponseValidator();
		objectMapper = new ObjectMapper();

		String baseUrl = authHandler.getBaseUrl();
		if (baseUrl == null || baseUrl.isEmpty()) {
			RestAssured.baseURI = BASE_URI;
		}
		else {
			RestAssured.baseURI = baseUrl;
		}

		parameters = getParameters();
		security = getSecurityInfo();
		schemas = getResponseSchemas();

		logger.info("✓ Test setup completed. Base URI: {}", RestAssured.baseURI);
	}

	public Stream<TestScenario> testScenarioProvider() {
		List<Map<String, Object>> testCases = loadTestData();
		if (testCases == null || testCases.isEmpty()) {
			logger.warn("✗ No test cases found in: {}", TEST_DATA_FILE);
			return Stream.empty();
		}

		int[] index = { 0 };
		return testCases.stream().map(testCase -> {
			index[0]++;
			String scenarioId = String.valueOf(index[0]);
			String scenarioDescription = testCase.containsKey("scenario") ? String.valueOf(testCase.get("scenario"))
					: "Test case " + scenarioId;
			String testName = generateTestName(scenarioDescription, testCase);
			return new TestScenario(scenarioId, testName, scenarioDescription, testCase);
		});
	}

	private String generateTestName(String scenario, Map<String, Object> testCase) {
		Object statusCodeObj = testCase.get("expected_statusCode");
		String statusCode = statusCodeObj != null ? String.valueOf(((Number) statusCodeObj).intValue()) : "unknown";

		String sanitized = scenario.replaceAll("[^a-zA-Z0-9]", "_").replaceAll("_+", "_").replaceAll("^_|_$", "");

		if (sanitized.length() > 50) {
			sanitized = sanitized.substring(0, 50);
		}

		return "test_" + sanitized + "_" + statusCode;
	}

	@ParameterizedTest(name = "[{index}] {0}")
	@MethodSource("testScenarioProvider")
	public void testEndpoint(TestScenario scenario) {
		logger.info("▶ Starting test: {} (ID: {})", scenario.testName, scenario.scenarioId);

		Map<String, Object> testCase = scenario.testCase;
		Object statusCodeObj = testCase.get("expected_statusCode");

		if (statusCodeObj == null) {
			logger.error("✗ Missing expected_statusCode in test case: {}", scenario.scenarioId);
			throw new AssertionError("Missing expected_statusCode in test case");
		}

		int expectedStatusCode = ((Number) statusCodeObj).intValue();
		String authValidityType = (expectedStatusCode == 401) ? "invalid" : "valid";

		logger.info("  Expected status: {}, Auth type: {}", expectedStatusCode, authValidityType);

		Response response = executeTest(testCase, parameters, security, authValidityType);

		ResponseSchema schema = schemas.get(expectedStatusCode);
		if (schema == null) {
			schema = schemas.get(0);
		}

		String contentType = response.getHeader("Content-Type");

		if (contentType != null && contentType.contains("application/json")) {
			responseValidator.validateResponse(response, expectedStatusCode, schema);
			logger.info("  ✓ Response validation completed");
		}
		else {
			if (response.getStatusCode() == expectedStatusCode) {
				logger.info("  ✓ Status code matches: {}", expectedStatusCode);
			}
			else {
				throw new AssertionError("Status code mismatch. Expected: " + expectedStatusCode + ", Actual: "
						+ response.getStatusCode());
			}
		}

		logger.info("✓ Test passed: {} (ID: {})", scenario.testName, scenario.scenarioId);
	}

	private Response executeTest(Map<String, Object> testCase, Map<String, ParameterInfo> parameters,
			SecurityInfo security, String authValidityType) {
		Map<String, Object> queryParams = new HashMap<>();
		Map<String, Object> pathParams = new HashMap<>();
		Map<String, Object> headerParams = new HashMap<>();
		Map<String, Object> bodyParams = new HashMap<>();

		for (Map.Entry<String, Object> entry : testCase.entrySet()) {
			String key = entry.getKey();
			Object value = entry.getValue();

			if (key.equals("scenario") || key.equals("expected_statusCode") || key.equals("ScenarioID")
					|| key.equals("TestName") || key.equals("Description") || key.equals("Execution")
					|| key.equals("Validation")) {
				continue;
			}

			if (value == null) {
				continue;
			}

			if (key.equals("headers") && value instanceof Map) {
				@SuppressWarnings("unchecked")
				Map<String, Object> headers = (Map<String, Object>) value;
				headerParams.putAll(headers);
				continue;
			}

			if (key.equals("query") && value instanceof Map) {
				@SuppressWarnings("unchecked")
				Map<String, Object> query = (Map<String, Object>) value;
				queryParams.putAll(query);
				continue;
			}

			if (key.equals("path") && value instanceof Map) {
				@SuppressWarnings("unchecked")
				Map<String, Object> path = (Map<String, Object>) value;
				pathParams.putAll(path);
				continue;
			}

			ParameterInfo paramInfo = parameters.get(key);
			if (paramInfo != null) {
				String location = paramInfo.getLocation();
				switch (location) {
					case "query":
						queryParams.put(key, value);
						break;
					case "path":
						pathParams.put(key, value);
						break;
					case "header":
						headerParams.put(key, value);
						break;
					case "body":
						bodyParams.put(key, value);
						break;
					default:
						bodyParams.put(key, value);
				}
			}
			else {
				bodyParams.put(key, value);
			}
		}

		RequestSpecification request = given().contentType(ContentType.JSON).accept(ContentType.JSON);

		if (security != null && security.getSchemeName() != null) {
			request = authHandler.applyAuth(request, security.getSchemeName(), authValidityType);
		}

		if (!queryParams.isEmpty()) {
			request = request.queryParams(queryParams);
		}

		if (!pathParams.isEmpty()) {
			request = request.pathParams(pathParams);
		}

		if (!headerParams.isEmpty()) {
			for (Map.Entry<String, Object> header : headerParams.entrySet()) {
				request = request.header(header.getKey(), header.getValue());
			}
		}

		if (!bodyParams.isEmpty()) {
			request = request.body(bodyParams);
		}

		logger.info("  Executing {} request to {}", HTTP_METHOD.toUpperCase(), ENDPOINT);

		Response response = request.when().post(ENDPOINT);

		logger.info("  Response status: {}", response.getStatusCode());

		return response;
	}

	private Map<String, ParameterInfo> getParameters() {
		Map<String, ParameterInfo> params = new HashMap<>();
		params.put("name", new ParameterInfo("name", "body", "string", true));
		params.put("description", new ParameterInfo("description", "body", "string", false));
		params.put("price", new ParameterInfo("price", "body", "number", true));
		params.put("currency", new ParameterInfo("currency", "body", "string", false));
		params.put("available", new ParameterInfo("available", "body", "boolean", false));
		return params;
	}

	private SecurityInfo getSecurityInfo() {
		return new SecurityInfo("bearerAuth", "http", "bearer", "header");
	}

	private Map<Integer, ResponseSchema> getResponseSchemas() {
		Map<Integer, ResponseSchema> schemaMap = new HashMap<>();

		// Schema for 201 response
		ResponseSchema schema201 = new ResponseSchema();
		Map<String, FieldConstraint> fields201 = new HashMap<>();

		fields201.put("id", new FieldConstraint("string"));
		fields201.put("name", new FieldConstraint("string"));
		fields201.put("description", new FieldConstraint("string"));
		fields201.put("price", new FieldConstraint("number").setFormat("float"));
		fields201.put("currency", new FieldConstraint("string"));
		fields201.put("available", new FieldConstraint("boolean"));
		fields201.put("createdAt", new FieldConstraint("string").setFormat("date-time"));

		schema201.setFields(fields201);
		schemaMap.put(201, schema201);

		// Schema for 400 response
		ResponseSchema schema400 = new ResponseSchema();
		Map<String, FieldConstraint> fields400 = new HashMap<>();

		fields400.put("code", new FieldConstraint("integer"));
		fields400.put("message", new FieldConstraint("string"));

		FieldConstraint detailsField = new FieldConstraint("array");
		detailsField.setItemsConstraint(new FieldConstraint("string"));
		fields400.put("details", detailsField);

		schema400.setFields(fields400);
		schemaMap.put(400, schema400);

		return schemaMap;
	}

	private List<Map<String, Object>> loadTestData() {
		try {
			File file = new File(TEST_DATA_FILE);
			if (!file.exists()) {
				logger.error("✗ Test data file not found: {}", TEST_DATA_FILE);
				return new ArrayList<>();
			}
			return objectMapper.readValue(file, new TypeReference<List<Map<String, Object>>>() {
			});
		}
		catch (IOException e) {
			logger.error("✗ Failed to load test data from {}: {}", TEST_DATA_FILE, e.getMessage());
			return new ArrayList<>();
		}
	}

	private static class TestScenario {

		private final String scenarioId;

		private final String testName;

		private final String description;

		private final Map<String, Object> testCase;

		public TestScenario(String scenarioId, String testName, String description, Map<String, Object> testCase) {
			this.scenarioId = scenarioId;
			this.testName = testName;
			this.description = description;
			this.testCase = testCase;
		}

		@Override
		public String toString() {
			return scenarioId + " - " + testName;
		}

	}

	private static class ParameterInfo {

		private final String name;

		private final String location;

		private final String type;

		private final boolean required;

		public ParameterInfo(String name, String location, String type, boolean required) {
			this.name = name;
			this.location = location;
			this.type = type;
			this.required = required;
		}

		public String getName() {
			return name;
		}

		public String getLocation() {
			return location;
		}

		public String getType() {
			return type;
		}

		public boolean isRequired() {
			return required;
		}

	}

	private static class SecurityInfo {

		private final String schemeName;

		private final String type;

		private final String credentialName;

		private final String location;

		public SecurityInfo(String schemeName, String type, String credentialName, String location) {
			this.schemeName = schemeName;
			this.type = type;
			this.credentialName = credentialName;
			this.location = location;
		}

		public String getSchemeName() {
			return schemeName;
		}

		public String getType() {
			return type;
		}

		public String getCredentialName() {
			return credentialName;
		}

		public String getLocation() {
			return location;
		}

	}

}
