// ********RoostGPT********
/*
Test generated by RoostGPT for test API-test-javaRest using AI Type Claude AI and AI Model claude-opus-4-5-20251101

Test generated for /users_post for http method type POST in rest-assured framework

RoostTestHash=ae63a5cc33

[
  {
    "ScenarioID": "1",
    "TestName": "testValidUserCreationReturns201",
    "Description": "Test creating a user with all valid required fields",
    "Execution": {
      "Arrange": "Prepare valid request body with username, email, firstName, lastName and valid bearer auth token",
      "Act": "Send POST request to /users with valid JSON body and Authorization header",
      "Assert": "Check for 201 status, response contains id, username, email, firstName, lastName, and createdAt fields"
    },
    "Validation": "Ensures API successfully creates a user with valid input and returns proper response structure"
  },
  {
    "ScenarioID": "2",
    "TestName": "testUserCreationWithMinimalFields",
    "Description": "Test creating a user with only required fields",
    "Execution": {
      "Arrange": "Prepare request body with only username and email, valid bearer token",
      "Act": "Send POST request to /users with minimal JSON body",
      "Assert": "Check for 201 status and response contains generated id and createdAt"
    },
    "Validation": "Ensures API accepts minimal required fields for user creation"
  },
  {
    "ScenarioID": "3",
    "TestName": "testMissingAuthorizationToken",
    "Description": "Test request without bearer authentication token",
    "Execution": {
      "Arrange": "Prepare valid request body but omit Authorization header",
      "Act": "Send POST request to /users without Authorization header",
      "Assert": "Check for 401 or 403 status indicating unauthorized access"
    },
    "Validation": "Ensures API enforces authentication and rejects unauthenticated requests"
  },
  {
    "ScenarioID": "4",
    "TestName": "testInvalidAuthorizationToken",
    "Description": "Test request with malformed or invalid bearer token",
    "Execution": {
      "Arrange": "Prepare valid request body with invalid bearer token like 'Bearer invalid_token_xyz'",
      "Act": "Send POST request to /users with invalid Authorization header",
      "Assert": "Check for 401 or 403 status indicating authentication failure"
    },
    "Validation": "Ensures API validates token authenticity and rejects invalid tokens"
  },
  {
    "ScenarioID": "5",
    "TestName": "testExpiredAuthorizationToken",
    "Description": "Test request with expired bearer token",
    "Execution": {
      "Arrange": "Prepare valid request body with expired bearer token",
      "Act": "Send POST request to /users with expired Authorization header",
      "Assert": "Check for 401 status indicating token expiration"
    },
    "Validation": "Ensures API rejects expired authentication tokens"
  },
  {
    "ScenarioID": "6",
    "TestName": "testMissingRequestBody",
    "Description": "Test request with no body content",
    "Execution": {
      "Arrange": "Prepare valid bearer token but no request body",
      "Act": "Send POST request to /users with empty body",
      "Assert": "Check for 400 status with error message indicating missing body"
    },
    "Validation": "Ensures API returns 400 when request body is missing"
  },
  {
    "ScenarioID": "7",
    "TestName": "testEmptyRequestBody",
    "Description": "Test request with empty JSON object",
    "Execution": {
      "Arrange": "Prepare valid bearer token and empty JSON object {}",
      "Act": "Send POST request to /users with empty JSON body",
      "Assert": "Check for 400 status with details about missing required fields"
    },
    "Validation": "Ensures API validates required fields and returns appropriate error"
  },
  {
    "ScenarioID": "8",
    "TestName": "testInvalidEmailFormat",
    "Description": "Test request with invalid email format",
    "Execution": {
      "Arrange": "Prepare request body with email as 'invalid-email-format' without @ symbol",
      "Act": "Send POST request to /users with invalid email",
      "Assert": "Check for 400 status with error details mentioning invalid email format"
    },
    "Validation": "Ensures API validates email format according to RFC standards"
  },
  {
    "ScenarioID": "9",
    "TestName": "testEmailWithoutDomain",
    "Description": "Test request with email missing domain part",
    "Execution": {
      "Arrange": "Prepare request body with email as 'user@'",
      "Act": "Send POST request to /users with incomplete email",
      "Assert": "Check for 400 status indicating invalid email"
    },
    "Validation": "Ensures API rejects emails without proper domain"
  },
  {
    "ScenarioID": "10",
    "TestName": "testEmailWithSpecialCharacters",
    "Description": "Test request with email containing special characters",
    "Execution": {
      "Arrange": "Prepare request body with email as 'user+test@example.com'",
      "Act": "Send POST request to /users with special character email",
      "Assert": "Check for 201 status as plus addressing is valid email format"
    },
    "Validation": "Ensures API accepts valid email formats with special characters"
  },
  {
    "ScenarioID": "11",
    "TestName": "testNullUsername",
    "Description": "Test request with null username value",
    "Execution": {
      "Arrange": "Prepare request body with username set to null",
      "Act": "Send POST request to /users with null username",
      "Assert": "Check for 400 status with error about invalid username"
    },
    "Validation": "Ensures API rejects null values for required string fields"
  },
  {
    "ScenarioID": "12",
    "TestName": "testEmptyStringUsername",
    "Description": "Test request with empty string username",
    "Execution": {
      "Arrange": "Prepare request body with username as empty string ''",
      "Act": "Send POST request to /users with empty username",
      "Assert": "Check for 400 status with validation error"
    },
    "Validation": "Ensures API rejects empty string for username field"
  },
  {
    "ScenarioID": "13",
    "TestName": "testUsernameWithSpacesOnly",
    "Description": "Test request with username containing only whitespace",
    "Execution": {
      "Arrange": "Prepare request body with username as '   '",
      "Act": "Send POST request to /users with whitespace username",
      "Assert": "Check for 400 status indicating invalid username"
    },
    "Validation": "Ensures API trims and validates username is not blank"
  },
  {
    "ScenarioID": "14",
    "TestName": "testUsernameWithSpecialCharacters",
    "Description": "Test request with username containing special characters",
    "Execution": {
      "Arrange": "Prepare request body with username as 'user@name!#$'",
      "Act": "Send POST request to /users with special character username",
      "Assert": "Check response status based on API username policy"
    },
    "Validation": "Ensures API enforces username character restrictions if any"
  },
  {
    "ScenarioID": "15",
    "TestName": "testVeryLongUsername",
    "Description": "Test request with extremely long username exceeding typical limits",
    "Execution": {
      "Arrange": "Prepare request body with username of 500 characters",
      "Act": "Send POST request to /users with very long username",
      "Assert": "Check for 400 status with error about username length"
    },
    "Validation": "Ensures API enforces maximum length constraints on username"
  },
  {
    "ScenarioID": "16",
    "TestName": "testNumericUsername",
    "Description": "Test request with purely numeric username",
    "Execution": {
      "Arrange": "Prepare request body with username as '12345678'",
      "Act": "Send POST request to /users with numeric username",
      "Assert": "Check response based on API username policy"
    },
    "Validation": "Ensures API handles numeric-only usernames appropriately"
  },
  {
    "ScenarioID": "17",
    "TestName": "testWrongTypeForUsername",
    "Description": "Test request with wrong data type for username field",
    "Execution": {
      "Arrange": "Prepare request body with username as integer 12345 instead of string",
      "Act": "Send POST request to /users with integer username",
      "Assert": "Check for 400 status with type mismatch error"
    },
    "Validation": "Ensures API validates data types and rejects wrong types"
  },
  {
    "ScenarioID": "18",
    "TestName": "testWrongTypeForEmail",
    "Description": "Test request with wrong data type for email field",
    "Execution": {
      "Arrange": "Prepare request body with email as boolean true instead of string",
      "Act": "Send POST request to /users with boolean email",
      "Assert": "Check for 400 status with type validation error"
    },
    "Validation": "Ensures API validates email field type"
  },
  {
    "ScenarioID": "19",
    "TestName": "testArrayTypeForUsername",
    "Description": "Test request with array type for username field",
    "Execution": {
      "Arrange": "Prepare request body with username as array ['user1', 'user2']",
      "Act": "Send POST request to /users with array username",
      "Assert": "Check for 400 status with type error"
    },
    "Validation": "Ensures API rejects array when string is expected"
  },
  {
    "ScenarioID": "20",
    "TestName": "testObjectTypeForEmail",
    "Description": "Test request with object type for email field",
    "Execution": {
      "Arrange": "Prepare request body with email as object {value: 'test@test.com'}",
      "Act": "Send POST request to /users with object email",
      "Assert": "Check for 400 status with type validation error"
    },
    "Validation": "Ensures API rejects object when string is expected"
  },
  {
    "ScenarioID": "21",
    "TestName": "testDuplicateUsername",
    "Description": "Test creating user with already existing username",
    "Execution": {
      "Arrange": "Create a user first, then prepare request with same username",
      "Act": "Send POST request to /users with duplicate username",
      "Assert": "Check for 400 or 409 status indicating duplicate"
    },
    "Validation": "Ensures API prevents duplicate usernames"
  },
  {
    "ScenarioID": "22",
    "TestName": "testDuplicateEmail",
    "Description": "Test creating user with already existing email",
    "Execution": {
      "Arrange": "Create a user first, then prepare request with same email",
      "Act": "Send POST request to /users with duplicate email",
      "Assert": "Check for 400 or 409 status indicating email already exists"
    },
    "Validation": "Ensures API prevents duplicate email addresses"
  },
  {
    "ScenarioID": "23",
    "TestName": "testMalformedJsonBody",
    "Description": "Test request with malformed JSON syntax",
    "Execution": {
      "Arrange": "Prepare malformed JSON like '{username: jdoe, email: test@test.com'",
      "Act": "Send POST request to /users with malformed JSON",
      "Assert": "Check for 400 status with JSON parse error"
    },
    "Validation": "Ensures API handles malformed JSON gracefully"
  },
  {
    "ScenarioID": "24",
    "TestName": "testWrongContentType",
    "Description": "Test request with incorrect Content-Type header",
    "Execution": {
      "Arrange": "Prepare valid JSON body but set Content-Type to text/plain",
      "Act": "Send POST request to /users with wrong Content-Type",
      "Assert": "Check for 400 or 415 status indicating unsupported media type"
    },
    "Validation": "Ensures API validates Content-Type header"
  },
  {
    "ScenarioID": "25",
    "TestName": "testXmlContentType",
    "Description": "Test request with XML content type and body",
    "Execution": {
      "Arrange": "Prepare XML body and set Content-Type to application/xml",
      "Act": "Send POST request to /users with XML content",
      "Assert": "Check for 400 or 415 status as API expects JSON"
    },
    "Validation": "Ensures API only accepts application/json content type"
  },
  {
    "ScenarioID": "26",
    "TestName": "testExtraUnknownFields",
    "Description": "Test request with additional unknown fields in body",
    "Execution": {
      "Arrange": "Prepare valid body with extra fields like 'unknownField': 'value'",
      "Act": "Send POST request to /users with extra fields",
      "Assert": "Check for 201 status, extra fields should be ignored or 400 if strict"
    },
    "Validation": "Ensures API handles unknown fields appropriately"
  },
  {
    "ScenarioID": "27",
    "TestName": "testNullEmail",
    "Description": "Test request with null email value",
    "Execution": {
      "Arrange": "Prepare request body with email set to null",
      "Act": "Send POST request to /users with null email",
      "Assert": "Check for 400 status with validation error for email"
    },
    "Validation": "Ensures API rejects null email values"
  },
  {
    "ScenarioID": "28",
    "TestName": "testNullFirstName",
    "Description": "Test request with null firstName value",
    "Execution": {
      "Arrange": "Prepare valid username and email with firstName as null",
      "Act": "Send POST request to /users with null firstName",
      "Assert": "Check response based on whether firstName is required"
    },
    "Validation": "Ensures API handles null optional fields correctly"
  },
  {
    "ScenarioID": "29",
    "TestName": "testNullLastName",
    "Description": "Test request with null lastName value",
    "Execution": {
      "Arrange": "Prepare valid username and email with lastName as null",
      "Act": "Send POST request to /users with null lastName",
      "Assert": "Check response based on whether lastName is required"
    },
    "Validation": "Ensures API handles null optional fields correctly"
  },
  {
    "ScenarioID": "30",
    "TestName": "testUnicodeCharactersInUsername",
    "Description": "Test request with unicode characters in username",
    "Execution": {
      "Arrange": "Prepare request body with username containing unicode like 'user_unicode'",
      "Act": "Send POST request to /users with unicode username",
      "Assert": "Check response based on API unicode support policy"
    },
    "Validation": "Ensures API handles unicode characters in username"
  },
  {
    "ScenarioID": "31",
    "TestName": "testUnicodeCharactersInNames",
    "Description": "Test request with unicode characters in firstName and lastName",
    "Execution": {
      "Arrange": "Prepare request body with firstName and lastName containing unicode characters",
      "Act": "Send POST request to /users with unicode names",
      "Assert": "Check for 201 status as names should support international characters"
    },
    "Validation": "Ensures API supports international characters in name fields"
  },
  {
    "ScenarioID": "32",
    "TestName": "testSqlInjectionInUsername",
    "Description": "Test request with SQL injection attempt in username",
    "Execution": {
      "Arrange": "Prepare request body with username as 'admin; DROP TABLE users;--'",
      "Act": "Send POST request to /users with SQL injection payload",
      "Assert": "Check for 400 status or 201 with sanitized input, no server error"
    },
    "Validation": "Ensures API is protected against SQL injection attacks"
  },
  {
    "ScenarioID": "33",
    "TestName": "testXssInjectionInFirstName",
    "Description": "Test request with XSS script injection in firstName",
    "Execution": {
      "Arrange": "Prepare request body with firstName as '<script>alert(1)</script>'",
      "Act": "Send POST request to /users with XSS payload",
      "Assert": "Check for 400 status or 201 with sanitized/escaped output"
    },
    "Validation": "Ensures API sanitizes input to prevent XSS attacks"
  },
  {
    "ScenarioID": "34",
    "TestName": "testVeryLongEmail",
    "Description": "Test request with extremely long email address",
    "Execution": {
      "Arrange": "Prepare request body with email of 300 characters",
      "Act": "Send POST request to /users with very long email",
      "Assert": "Check for 400 status with email length validation error"
    },
    "Validation": "Ensures API enforces maximum length on email field"
  },
  {
    "ScenarioID": "35",
    "TestName": "testCaseSensitivityUsername",
    "Description": "Test username case sensitivity by creating similar usernames",
    "Execution": {
      "Arrange": "Create user with username 'JDoe', then try 'jdoe'",
      "Act": "Send POST request to /users with different case username",
      "Assert": "Check if API treats usernames as case-insensitive or case-sensitive"
    },
    "Validation": "Ensures API handles username case sensitivity consistently"
  },
  {
    "ScenarioID": "36",
    "TestName": "testCaseSensitivityEmail",
    "Description": "Test email case sensitivity",
    "Execution": {
      "Arrange": "Create user with email 'Test@Example.com', then try 'test@example.com'",
      "Act": "Send POST request to /users with different case email",
      "Assert": "Check if API treats emails as case-insensitive per RFC"
    },
    "Validation": "Ensures API handles email case sensitivity correctly"
  },
  {
    "ScenarioID": "37",
    "TestName": "testBearerTokenWithoutBearerPrefix",
    "Description": "Test authorization header without Bearer prefix",
    "Execution": {
      "Arrange": "Prepare valid request body with Authorization header as just the token without 'Bearer '",
      "Act": "Send POST request to /users with malformed auth header",
      "Assert": "Check for 401 status indicating invalid authorization format"
    },
    "Validation": "Ensures API validates Bearer token format strictly"
  },
  {
    "ScenarioID": "38",
    "TestName": "testEmptyBearerToken",
    "Description": "Test authorization header with empty token value",
    "Execution": {
      "Arrange": "Prepare valid request body with Authorization header as 'Bearer '",
      "Act": "Send POST request to /users with empty bearer token",
      "Assert": "Check for 401 status indicating missing token"
    },
    "Validation": "Ensures API rejects empty bearer tokens"
  },
  {
    "ScenarioID": "39",
    "TestName": "testResponseContainsId",
    "Description": "Verify response contains auto-generated user id",
    "Execution": {
      "Arrange": "Prepare valid request body with all fields",
      "Act": "Send POST request to /users with valid data",
      "Assert": "Check 201 status and response body contains 'id' field with string value"
    },
    "Validation": "Ensures API generates and returns user id in response"
  },
  {
    "ScenarioID": "40",
    "TestName": "testResponseContainsCreatedAt",
    "Description": "Verify response contains createdAt timestamp",
    "Execution": {
      "Arrange": "Prepare valid request body with all fields",
      "Act": "Send POST request to /users with valid data",
      "Assert": "Check 201 status and response contains 'createdAt' in ISO 8601 date-time format"
    },
    "Validation": "Ensures API generates and returns creation timestamp"
  },
  {
    "ScenarioID": "41",
    "TestName": "testResponseMatchesRequestData",
    "Description": "Verify response echoes back the submitted user data",
    "Execution": {
      "Arrange": "Prepare request body with username 'testuser', email 'test@test.com'",
      "Act": "Send POST request to /users with specific data",
      "Assert": "Check 201 status and response username and email match request"
    },
    "Validation": "Ensures API returns correct user data in response"
  },
  {
    "ScenarioID": "42",
    "TestName": "testLeadingTrailingSpacesInUsername",
    "Description": "Test request with leading and trailing spaces in username",
    "Execution": {
      "Arrange": "Prepare request body with username as '  jdoe  '",
      "Act": "Send POST request to /users with padded username",
      "Assert": "Check if API trims spaces or returns 400"
    },
    "Validation": "Ensures API handles whitespace in username appropriately"
  },
  {
    "ScenarioID": "43",
    "TestName": "testLeadingTrailingSpacesInEmail",
    "Description": "Test request with leading and trailing spaces in email",
    "Execution": {
      "Arrange": "Prepare request body with email as '  test@test.com  '",
      "Act": "Send POST request to /users with padded email",
      "Assert": "Check if API trims spaces or returns 400"
    },
    "Validation": "Ensures API handles whitespace in email appropriately"
  },
  {
    "ScenarioID": "44",
    "TestName": "testHttpMethodGet",
    "Description": "Test using GET method instead of POST",
    "Execution": {
      "Arrange": "Prepare valid request body and auth token",
      "Act": "Send GET request to /users with body",
      "Assert": "Check for 405 Method Not Allowed status"
    },
    "Validation": "Ensures API only accepts POST method for user creation"
  },
  {
    "ScenarioID": "45",
    "TestName": "testHttpMethodPut",
    "Description": "Test using PUT method instead of POST",
    "Execution": {
      "Arrange": "Prepare valid request body and auth token",
      "Act": "Send PUT request to /users with body",
      "Assert": "Check for 405 Method Not Allowed status"
    },
    "Validation": "Ensures API rejects PUT method on create endpoint"
  },
  {
    "ScenarioID": "46",
    "TestName": "testConcurrentUserCreation",
    "Description": "Test concurrent requests to create users with same data",
    "Execution": {
      "Arrange": "Prepare two identical request bodies with same username",
      "Act": "Send two POST requests to /users simultaneously",
      "Assert": "Check one succeeds with 201, other fails with 400 or 409"
    },
    "Validation": "Ensures API handles race conditions for duplicate prevention"
  },
  {
    "ScenarioID": "47",
    "TestName": "testIdempotencyWithSameData",
    "Description": "Test multiple requests with identical data",
    "Execution": {
      "Arrange": "Prepare valid request body",
      "Act": "Send same POST request to /users twice sequentially",
      "Assert": "First returns 201, second returns 400 or 409 for duplicate"
    },
    "Validation": "Ensures API is not idempotent and prevents duplicates"
  },
  {
    "ScenarioID": "48",
    "TestName": "testEmailWithMultipleAtSymbols",
    "Description": "Test request with email containing multiple @ symbols",
    "Execution": {
      "Arrange": "Prepare request body with email as 'user@@example.com'",
      "Act": "Send POST request to /users with invalid email",
      "Assert": "Check for 400 status with email format error"
    },
    "Validation": "Ensures API validates email format correctly"
  },
  {
    "ScenarioID": "49",
    "TestName": "testResponseContentType",
    "Description": "Verify response has correct Content-Type header",
    "Execution": {
      "Arrange": "Prepare valid request body and auth token",
      "Act": "Send POST request to /users with valid data",
      "Assert": "Check 201 status and Content-Type header is application/json"
    },
    "Validation": "Ensures API returns proper content type in response"
  },
  {
    "ScenarioID": "50",
    "TestName": "testErrorResponseStructure",
    "Description": "Verify 400 error response matches expected schema",
    "Execution": {
      "Arrange": "Prepare invalid request body to trigger 400 error",
      "Act": "Send POST request to /users with invalid data",
      "Assert": "Check 400 status and response contains code, message, and details array"
    },
    "Validation": "Ensures API returns properly structured error responses"
  }
]

*/

// ********RoostGPT********
package org.petstore.example.RoostTest.openapi_configuration;

import org.petstore.example.RoostTest.openapi_configuration.auth.UnifiedAuthHandler;
import org.petstore.example.RoostTest.openapi_configuration.utils.ResponseValidator;
import org.petstore.example.RoostTest.openapi_configuration.utils.SchemaModels.ResponseSchema;
import org.petstore.example.RoostTest.openapi_configuration.utils.SchemaModels.FieldConstraint;
import org.petstore.example.RoostTest.openapi_configuration.utils.SchemaModels.NumericConstraint;
import org.petstore.example.RoostTest.openapi_configuration.utils.SchemaModels.StringConstraint;
import org.petstore.example.RoostTest.openapi_configuration.utils.SchemaModels.ArrayConstraint;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import io.restassured.http.ContentType;
import static io.restassured.RestAssured.given;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.AfterAll;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.File;
import java.io.IOException;
import java.util.*;

public class UsersPostTest {

	private static final Logger logger = LoggerFactory.getLogger(UsersPostTest.class);

	private static UnifiedAuthHandler authHandler;

	private static ResponseValidator responseValidator;

	private static ObjectMapper objectMapper;

	private static final String BASE_URI = "http://localhost:8080/OpenAPIExample/";

	private static final String ENDPOINT = "/users";

	private static final String HTTP_METHOD = "post";

	private static final String TEST_DATA_FILE = "src/test/java/org/petstore/example/RoostTest/openapi_configuration/datasets/usersPostTest.json";

	private static List<String> failedTests = new ArrayList<>();

	private static int totalTests = 0;

	private static int passedTests = 0;

	private static int failedTestsCount = 0;

	@BeforeAll
	public static void setup() {
		authHandler = new UnifiedAuthHandler();
		responseValidator = new ResponseValidator();
		objectMapper = new ObjectMapper();

		String baseUrl = authHandler.getBaseUrl();
		if (baseUrl == null || baseUrl.isEmpty()) {
			RestAssured.baseURI = BASE_URI;
		}
		else {
			RestAssured.baseURI = baseUrl;
		}

		logger.info("Test setup completed. Base URI: {}", RestAssured.baseURI);
	}

	@Test
	public void testEndpoint() {
		List<Map<String, Object>> testCases = loadTestData();
		Map<String, ParameterInfo> parameters = getParameters();
		SecurityInfo security = getSecurityInfo();
		Map<Integer, ResponseSchema> schemas = getResponseSchemas();

		for (Map<String, Object> testCase : testCases) {
			totalTests++;
			String scenario = testCase.containsKey("scenario") ? testCase.get("scenario").toString()
					: "Test case " + totalTests;

			try {
				logger.info("Executing test {}/{}: {}", totalTests, testCases.size(), scenario);

				Object statusCodeObj = testCase.get("expected_statusCode");
				if (statusCodeObj == null) {
					logger.error("Test case missing 'expected_statusCode' field: {}", scenario);
					failedTests.add(scenario + " - Missing expected_statusCode");
					failedTestsCount++;
					continue;
				}
				int expectedStatusCode = ((Number) statusCodeObj).intValue();

				String authValidityType = (expectedStatusCode == 401) ? "invalid" : "valid";

				Response response = executeTest(testCase, parameters, security, authValidityType);

				ResponseSchema schema = schemas.get(expectedStatusCode);
				if (schema == null) {
					schema = schemas.get(0);
				}

				String contentType = response.getHeader("Content-Type");
				if (contentType != null && contentType.toLowerCase().contains("application/json")) {
					responseValidator.validateResponse(response, expectedStatusCode, schema);
					logger.info("Response validation completed for JSON content type");
				}
				else {
					if (response.getStatusCode() == expectedStatusCode) {
						logger.info(
								"Status code validation passed: expected {}, actual {}. Response body validation skipped for content-type: {}",
								expectedStatusCode, response.getStatusCode(),
								contentType != null ? contentType : "not specified");
					}
					else {
						throw new AssertionError(String.format(
								"Status code mismatch: expected %d, but got %d. Response body validation skipped for content-type: %s",
								expectedStatusCode, response.getStatusCode(),
								contentType != null ? contentType : "not specified"));
					}
				}

				passedTests++;
				logger.info("✓ Test passed: {}", scenario);

			}
			catch (Throwable e) {
				failedTestsCount++;
				failedTests.add(scenario + " - " + e.getMessage());
				logger.error("✗ Test failed: {} - Error: {}", scenario, e.getMessage());
			}
		}
	}

	@AfterAll
	public static void tearDown() {
		logger.info("\n=== Test Execution Summary ===");
		logger.info("Total tests: {}", totalTests);
		logger.info("Passed: {}", passedTests);
		logger.info("Failed: {}", failedTestsCount);

		if (failedTestsCount > 0) {
			logger.info("\nFailed test scenarios:");
			for (String failedTest : failedTests) {
				logger.info("  - {}", failedTest);
			}
		}
	}

	private Response executeTest(Map<String, Object> testCase, Map<String, ParameterInfo> parameters,
			SecurityInfo security, String authValidityType) {
		Map<String, Object> queryParams = new HashMap<>();
		Map<String, Object> pathParams = new HashMap<>();
		Map<String, Object> headerParams = new HashMap<>();
		Map<String, Object> bodyParams = new HashMap<>();

		for (Map.Entry<String, Object> entry : testCase.entrySet()) {
			String key = entry.getKey();
			Object value = entry.getValue();

			if (key.equals("scenario") || key.equals("expected_statusCode")) {
				continue;
			}

			ParameterInfo paramInfo = parameters.get(key);
			if (paramInfo != null) {
				String location = paramInfo.getLocation();
				switch (location) {
					case "query":
						queryParams.put(key, value);
						break;
					case "path":
						pathParams.put(key, value);
						break;
					case "header":
						headerParams.put(key, value);
						break;
					case "body":
						bodyParams.put(key, value);
						break;
					default:
						bodyParams.put(key, value);
						break;
				}
			}
			else {
				bodyParams.put(key, value);
			}
		}

		RequestSpecification request = given().contentType(ContentType.JSON).accept(ContentType.JSON);

		if (security != null && security.getSchemeName() != null && authHandler.hasScheme(security.getSchemeName())) {
			request = authHandler.applyAuth(request, security.getSchemeName(), authValidityType);
		}

		if (!queryParams.isEmpty()) {
			request = request.queryParams(queryParams);
		}

		if (!pathParams.isEmpty()) {
			request = request.pathParams(pathParams);
		}

		if (!headerParams.isEmpty()) {
			for (Map.Entry<String, Object> header : headerParams.entrySet()) {
				request = request.header(header.getKey(), header.getValue());
			}
		}

		if (!bodyParams.isEmpty()) {
			request = request.body(bodyParams);
		}

		return request.when().post(ENDPOINT);
	}

	private Map<String, ParameterInfo> getParameters() {
		Map<String, ParameterInfo> parameters = new HashMap<>();
		parameters.put("username", new ParameterInfo("username", "body", "string", true));
		parameters.put("email", new ParameterInfo("email", "body", "string", true));
		parameters.put("password", new ParameterInfo("password", "body", "string", true));
		return parameters;
	}

	private SecurityInfo getSecurityInfo() {
		return new SecurityInfo("bearerAuth", "http", "bearer", "header");
	}

	private Map<Integer, ResponseSchema> getResponseSchemas() {
		Map<Integer, ResponseSchema> schemas = new HashMap<>();

		// Schema for 201 response
		ResponseSchema schema201 = new ResponseSchema();
		Map<String, FieldConstraint> fields201 = new HashMap<>();

		fields201.put("id", new FieldConstraint("string"));
		fields201.put("username", new FieldConstraint("string"));
		fields201.put("email", new FieldConstraint("string").setFormat("email"));
		fields201.put("firstName", new FieldConstraint("string"));
		fields201.put("lastName", new FieldConstraint("string"));
		fields201.put("createdAt", new FieldConstraint("string").setFormat("date-time"));

		schema201.setFields(fields201);
		schemas.put(201, schema201);

		// Schema for 400 response
		ResponseSchema schema400 = new ResponseSchema();
		Map<String, FieldConstraint> fields400 = new HashMap<>();

		fields400.put("code", new FieldConstraint("integer"));
		fields400.put("message", new FieldConstraint("string"));

		FieldConstraint detailsField = new FieldConstraint("array");
		detailsField.setItemsConstraint(new FieldConstraint("string"));
		fields400.put("details", detailsField);

		schema400.setFields(fields400);
		schemas.put(400, schema400);

		return schemas;
	}

	private List<Map<String, Object>> loadTestData() {
		try {
			File file = new File(TEST_DATA_FILE);
			return objectMapper.readValue(file, new TypeReference<List<Map<String, Object>>>() {
			});
		}
		catch (IOException e) {
			logger.error("Failed to load test data from {}: {}", TEST_DATA_FILE, e.getMessage());
			return new ArrayList<>();
		}
	}

	private static class ParameterInfo {

		private final String name;

		private final String location;

		private final String type;

		private final boolean required;

		public ParameterInfo(String name, String location, String type, boolean required) {
			this.name = name;
			this.location = location;
			this.type = type;
			this.required = required;
		}

		public String getName() {
			return name;
		}

		public String getLocation() {
			return location;
		}

		public String getType() {
			return type;
		}

		public boolean isRequired() {
			return required;
		}

	}

	private static class SecurityInfo {

		private final String schemeName;

		private final String type;

		private final String credentialName;

		private final String location;

		public SecurityInfo(String schemeName, String type, String credentialName, String location) {
			this.schemeName = schemeName;
			this.type = type;
			this.credentialName = credentialName;
			this.location = location;
		}

		public String getSchemeName() {
			return schemeName;
		}

		public String getType() {
			return type;
		}

		public String getCredentialName() {
			return credentialName;
		}

		public String getLocation() {
			return location;
		}

	}

}
